Add stats (#4)
* Generate stats controller and add routes

* Add pry to console

* Add distance to trip factory

* Move stats requests spec to right folder

* Add stats weekly spec

* Add weekly method

* Add monthly stats

* Add monthly stats spec

* Add date ordering and date formatting to monthly stats

* Add timecop to abstract test from date it was created

* Change spec to response check and response details

* Move monthly stats creation to service

* Add rounding to 1 meter and .01 PLN

* Add spec to check for validation on addresses

* Add addresses validation

* Add validation messages specs

* Wrap specs in aggregate failures block

* Convert distances and prices to decimal
Use number helper currency to get price as currency string

* Add edge case found in previous manual tests
When day has at least one nil distance and one normal distance:
undefined method `+' for nil:NilClass in app/services/day_statistics_creator.rb:22 appears

* Fix error of nil distance by adding 0.0 distance as default
Why?
Since we do not approve same addresses wrong data will be easy to find.
It can be used in sum and average calculations